export type CatalogCategory = {
  id: string;
  name: string;
  subcategories: string[];
  products: string[];
};

/**
 * InstaBuy's broad quick-commerce assortment seed.
 * This mirrors the category breadth publicly described by Instamart;
 * it is a product taxonomy/seed list, not a claim of an exact live SKU dump.
 */
export const instamartCatalog: CatalogCategory[] = [
  { id: "fresh-vegetables", name: "Fresh Vegetables", subcategories: ["Daily Vegetables", "Leafy & Seasonings", "Exotic Vegetables", "Fresh Cuts", "Organic", "Festive Essentials"], products: ["Onion", "Potato", "Tomato", "Coriander", "Green Chilli", "Carrot", "Cucumber", "Capsicum", "Cauliflower", "Cabbage", "Lady Finger", "Brinjal", "Beans", "Peas", "Beetroot", "Radish", "Bottle Gourd", "Bitter Gourd", "Spinach", "Methi", "Ginger", "Garlic", "Lemon", "Sweet Corn", "Broccoli", "Mushroom", "Zucchini", "French Beans", "Drumstick", "Coconut"] },
  { id: "fresh-fruits", name: "Fresh Fruits", subcategories: ["Everyday Fruits", "Exotic Fruits", "Regional Favorites", "Mangoes & Melons", "Fresh Cuts", "Organic", "Combos"], products: ["Banana", "Apple", "Orange", "Mosambi", "Papaya", "Pomegranate", "Watermelon", "Muskmelon", "Grapes", "Guava", "Mango", "Pineapple", "Kiwi", "Strawberry", "Blueberry", "Pear", "Peach", "Plum", "Dragon Fruit", "Chikoo", "Custard Apple", "Coconut", "Avocado", "Fig", "Cherries", "Fruit Salad Cut", "Mixed Fruit Bowl"] },
  { id: "dairy-bread-eggs", name: "Dairy, Bread & Eggs", subcategories: ["Milk", "Bread & Buns", "Butter", "Cheese", "Curd & Yogurt", "Dairy Alternatives", "Eggs", "Indian Breads", "Paneer & Cream", "Lassi & Buttermilk", "Milk Drinks"], products: ["Toned Milk", "Full Cream Milk", "A2 Milk", "UHT Milk", "Brown Bread", "Whole Wheat Bread", "Multigrain Bread", "Burger Buns", "Pav", "Croissant", "Butter", "Cheese Slices", "Cheese Block", "Mozzarella", "Curd", "Greek Yogurt", "Flavoured Yogurt", "Paneer", "Tofu", "Fresh Cream", "Lassi", "Buttermilk", "Milkshake", "Probiotic Drink", "White Eggs", "Brown Eggs", "High Protein Eggs"] },
  { id: "rice-atta-dals", name: "Rice, Atta & Dals", subcategories: ["Rice", "Atta & Flour", "Dal", "Pulses", "Millets", "Poha & Breakfast Grains"], products: ["Basmati Rice", "Sona Masoori Rice", "Kolam Rice", "Brown Rice", "Idli Rice", "Rice Flour", "Wheat Atta", "Multigrain Atta", "Besan", "Maida", "Sooji", "Ragi Flour", "Jowar Flour", "Bajra Flour", "Toor Dal", "Moong Dal", "Masoor Dal", "Urad Dal", "Chana Dal", "Rajma", "Kabuli Chana", "Black Chana", "Green Moong", "Dalia", "Poha", "Quinoa"] },
  { id: "masalas-dry-fruits", name: "Masalas & Dry Fruits", subcategories: ["Whole Spices", "Powdered Spices", "Blended Masalas", "Dry Fruits", "Nuts & Seeds"], products: ["Turmeric Powder", "Red Chilli Powder", "Coriander Powder", "Cumin", "Black Pepper", "Garam Masala", "Chaat Masala", "Kitchen King Masala", "Pav Bhaji Masala", "Biryani Masala", "Sambar Masala", "Cinnamon", "Cardamom", "Cloves", "Bay Leaf", "Cashew", "Almond", "Pistachio", "Walnut", "Raisins", "Dates", "Pumpkin Seeds", "Sunflower Seeds", "Flax Seeds", "Chia Seeds", "Mixed Dry Fruits"] },
  { id: "oils-ghee", name: "Oils & Ghee", subcategories: ["Cooking Oils", "Ghee", "Cold Pressed Oils", "Specialty Oils"], products: ["Sunflower Oil", "Mustard Oil", "Groundnut Oil", "Rice Bran Oil", "Soybean Oil", "Olive Oil", "Coconut Oil", "Sesame Oil", "Fortified Oil", "Cold Pressed Groundnut Oil", "Cow Ghee", "Buffalo Ghee", "A2 Ghee", "Organic Ghee", "Butter Oil"] },
  { id: "munchies", name: "Munchies & Snacks", subcategories: ["Chips", "Namkeen", "Popcorn", "Nuts & Snacks", "Indian Snacks"], products: ["Potato Chips", "Masala Chips", "Banana Chips", "Nachos", "Tortilla Chips", "Aloo Bhujia", "Sev", "Mixture", "Bhujia", "Moong Dal", "Peanut Masala", "Popcorn", "Roasted Makhana", "Trail Mix", "Roasted Chana", "Chakli", "Khakhra", "Mathri", "Papad", "Snack Bars"] },
  { id: "sweet-tooth", name: "Sweet Tooth", subcategories: ["Chocolates", "Candies & Mints", "Indian Sweets", "Ice Cream", "Desserts"], products: ["Milk Chocolate", "Dark Chocolate", "White Chocolate", "Chocolate Bar", "Chocolate Box", "Gummy Candy", "Toffee", "Mint", "Gulab Jamun", "Rasgulla", "Soan Papdi", "Kaju Katli", "Besan Ladoo", "Jalebi", "Brownie", "Cake", "Ice Cream Tub", "Ice Cream Cone", "Kulfi", "Frozen Dessert", "Mithai Gift Box"] },
  { id: "cold-drinks-juices", name: "Cold Drinks & Juices", subcategories: ["Soft Drinks", "Juices", "Energy Drinks", "Sports Drinks", "Water", "Coconut Water"], products: ["Cola", "Lemon Lime Soft Drink", "Orange Soft Drink", "Soda", "Tonic Water", "Mango Juice", "Orange Juice", "Apple Juice", "Mixed Fruit Juice", "Coconut Water", "Energy Drink", "Sports Drink", "Iced Tea", "Cold Coffee", "Flavoured Milk", "Mineral Water", "Sparkling Water", "Packaged Water", "Electrolyte Drink"] },
  { id: "biscuits-cakes", name: "Biscuits & Cakes", subcategories: ["Biscuits", "Cookies", "Cream Biscuits", "Crackers", "Cakes", "Rusk"], products: ["Marie Biscuits", "Glucose Biscuits", "Digestive Biscuits", "Cream Biscuits", "Chocolate Biscuits", "Jeera Biscuits", "Salted Crackers", "Bourbon Biscuits", "Oat Cookies", "Butter Cookies", "Rusk", "Fruit Cake", "Tea Cake", "Chocolate Cake", "Cupcake", "Muffin", "Brownie Box"] },
  { id: "instant-frozen", name: "Instant & Frozen Food", subcategories: ["Instant Noodles", "Pasta", "Ready-to-Eat", "Frozen Snacks", "Frozen Vegetables", "Frozen Desserts"], products: ["Instant Noodles", "Cup Noodles", "Oats Noodles", "Pasta", "Macaroni", "Pasta Sauce", "Ready Poha", "Ready Upma", "Ready Paratha", "Frozen Samosa", "Frozen Spring Roll", "Frozen French Fries", "Frozen Peas", "Frozen Corn", "Frozen Mixed Vegetables", "Frozen Momos", "Frozen Nuggets", "Frozen Pizza", "Ready Dal", "Ready Paneer Curry"] },
  { id: "meat-seafood", name: "Meat & Seafood", subcategories: ["Chicken", "Mutton", "Fish", "Seafood", "Eggs & Ready-to-Cook"], products: ["Chicken Curry Cut", "Chicken Breast", "Chicken Wings", "Chicken Drumsticks", "Chicken Keema", "Mutton Curry Cut", "Mutton Keema", "Rohu Fish", "Surmai Fish", "Pomfret", "Prawns", "Fish Fillet", "Chicken Sausage", "Chicken Salami", "Marinated Chicken", "Ready-to-Cook Kebab"] },
  { id: "cereals-breakfast", name: "Cereals & Breakfast", subcategories: ["Corn Flakes", "Muesli", "Oats", "Granola", "Spreads", "Healthy Breakfast"], products: ["Corn Flakes", "Chocos", "Muesli", "Granola", "Rolled Oats", "Instant Oats", "Steel Cut Oats", "Poha", "Dalia", "Protein Cereal", "Peanut Butter", "Almond Butter", "Hazelnut Spread", "Honey", "Maple Syrup", "Jam", "Marmalade", "Pancake Mix"] },
  { id: "sauces-spreads", name: "Sauces & Spreads", subcategories: ["Ketchup", "Mayonnaise", "Cooking Sauces", "Dips", "Pickles", "Chutneys"], products: ["Tomato Ketchup", "Eggless Mayonnaise", "Chilli Sauce", "Schezwan Sauce", "Soy Sauce", "Pizza Pasta Sauce", "Mustard Sauce", "Barbecue Sauce", "Peri Peri Sauce", "Cheese Dip", "Salsa", "Peanut Chutney", "Mint Chutney", "Mango Pickle", "Mixed Pickle", "Vinegar", "Pasta Sauce"] },
  { id: "tea-coffee", name: "Tea, Coffee & More", subcategories: ["Tea", "Green Tea", "Coffee", "Hot Chocolate", "Premixes"], products: ["Assam Tea", "Darjeeling Tea", "Masala Tea", "Green Tea", "Black Tea", "Tea Bags", "Instant Coffee", "Filter Coffee", "Ground Coffee", "Cold Brew", "Hot Chocolate", "Cappuccino Premix", "Ginger Tea", "Lemon Tea", "Herbal Tea"] },
  { id: "cleaning-essentials", name: "Cleaning Essentials", subcategories: ["Laundry", "Dishwash", "Floor Care", "Toilet Care", "Surface Cleaners", "Air Care", "Pest Control"], products: ["Detergent Powder", "Liquid Detergent", "Detergent Pods", "Fabric Conditioner", "Dishwash Bar", "Dishwash Liquid", "Dishwasher Tablets", "Floor Cleaner", "Toilet Cleaner", "Bathroom Cleaner", "Glass Cleaner", "Kitchen Cleaner", "Disinfectant", "Air Freshener", "Mosquito Repellent", "Cockroach Killer", "Drain Cleaner", "Cleaning Gloves", "Microfiber Cloth", "Garbage Bags"] },
  { id: "pharma-hygiene", name: "Pharma & Hygiene", subcategories: ["Feminine Hygiene", "Sexual Wellness", "First Aid", "OTC Essentials", "Oral Care", "Hand Hygiene"], products: ["Sanitary Pads", "Panty Liners", "Tampons", "Menstrual Cups", "Adult Diapers", "Condoms", "Lubricant", "Bandages", "Antiseptic Liquid", "Cotton", "Gauze", "Thermometer", "Hand Sanitizer", "Hand Wash", "Toothpaste", "Toothbrush", "Mouthwash", "Dental Floss", "Tissues", "Wet Wipes"] },
  { id: "bath-body-hair", name: "Bath, Body & Hair", subcategories: ["Bath & Body", "Shampoo", "Conditioner", "Hair Care", "Deodorants", "Men's Grooming"], products: ["Bath Soap", "Body Wash", "Shampoo", "Anti-Dandruff Shampoo", "Conditioner", "Hair Oil", "Hair Serum", "Hair Color", "Body Lotion", "Body Scrub", "Hand Cream", "Deodorant", "Perfume", "Shaving Cream", "Razor", "After Shave", "Beard Oil", "Beard Trimmer", "Face Wash", "Sunscreen"] },
  { id: "home-kitchen", name: "Home & Kitchen", subcategories: ["Cookware", "Storage", "Dining", "Kitchen Tools", "Home Utility", "Decor"], products: ["Pressure Cooker", "Frying Pan", "Kadhai", "Tawa", "Saucepan", "Knife", "Chopping Board", "Peeler", "Grater", "Lunch Box", "Water Bottle", "Storage Container", "Glass Set", "Dinner Set", "Mug", "Plate", "Cutlery Set", "Kitchen Towels", "Aluminium Foil", "Cling Film", "Baking Tray", "Air Fryer", "Electric Kettle", "Mixer Grinder"] },
  { id: "office-stationery", name: "Office & Stationery", subcategories: ["Writing", "Paper", "School Supplies", "Office Supplies", "Art & Craft"], products: ["Ball Pen", "Gel Pen", "Pencil", "Eraser", "Sharpener", "Notebook", "Register", "Sticky Notes", "Marker", "Highlighter", "Printer Paper", "File Folder", "Stapler", "Staples", "Scissors", "Glue", "Tape", "Calculator", "Sketch Pens", "Color Pencils", "Crayons", "Craft Paper"] },
  { id: "baby-care", name: "Baby Care", subcategories: ["Baby Food & Formula", "Diapers & Wipes", "Bath & Hair", "Skin Care", "Baby Pharma", "Oral Care", "Accessories"], products: ["Baby Formula", "Baby Cereal", "Baby Porridge", "Diapers", "Newborn Diapers", "Baby Pants", "Baby Wipes", "Baby Shampoo", "Baby Soap", "Baby Body Wash", "Baby Lotion", "Baby Oil", "Diaper Rash Cream", "Baby Powder", "Baby Toothbrush", "Baby Feeding Bottle", "Sipper Cup", "Pacifier", "Baby Bib", "Baby Towels", "Teether"] },
  { id: "pet-supplies", name: "Pet Supplies", subcategories: ["Dog Food", "Cat Food", "Treats", "Grooming", "Pet Hygiene", "Accessories"], products: ["Adult Dog Food", "Puppy Food", "Adult Cat Food", "Kitten Food", "Dog Treats", "Cat Treats", "Dental Chews", "Wet Dog Food", "Wet Cat Food", "Cat Litter", "Pet Shampoo", "Pet Wipes", "Flea & Tick Care", "Pet Bowls", "Leash", "Collar", "Pet Toys", "Poop Bags"] },
  { id: "beauty-grooming", name: "Beauty & Grooming", subcategories: ["Skincare", "Makeup", "Hair Styling", "Fragrance", "Beauty Tools", "Men's Grooming"], products: ["Face Serum", "Moisturizer", "Cleanser", "Toner", "Sunscreen", "Lip Balm", "Face Mask", "Foundation", "Concealer", "Lipstick", "Kajal", "Eyeliner", "Mascara", "Blush", "Makeup Remover", "Hair Straightener", "Hair Dryer", "Curling Iron", "Nail Polish", "Nail Remover", "Perfume"] },
  { id: "electronics", name: "Electronics & Gadgets", subcategories: ["Mobiles", "Audio", "Chargers", "Smart Devices", "Accessories", "Small Appliances"], products: ["Smartphone", "Feature Phone", "Tablet", "Smartwatch", "Fitness Band", "Bluetooth Earbuds", "Bluetooth Speaker", "Headphones", "Power Bank", "Fast Charger", "USB Cable", "Charging Adapter", "Extension Board", "Keyboard", "Mouse", "Webcam", "Projector", "Air Purifier", "Trimmer", "Electric Toothbrush", "Electric Kettle", "Iron"] },
  { id: "home-appliances", name: "Home Appliances", subcategories: ["Kitchen Appliances", "Personal Appliances", "Cleaning Appliances", "Cooling & Heating"], products: ["Air Fryer", "Microwave Oven", "Mixer Grinder", "Juicer", "Induction Cooktop", "Electric Kettle", "Coffee Maker", "Toaster", "Hand Blender", "Rice Cooker", "Steam Iron", "Garment Steamer", "Vacuum Cleaner", "Room Heater", "Table Fan", "Air Cooler", "Humidifier"] },
  { id: "toys-games", name: "Toys & Games", subcategories: ["Educational Toys", "Board Games", "Building Sets", "Dolls", "Outdoor Play", "Puzzles"], products: ["Building Blocks", "Construction Set", "Doll", "Action Figure", "Toy Car", "Remote Control Car", "Board Game", "Card Game", "Chess", "Ludo", "Monopoly", "Puzzle", "Jigsaw Puzzle", "Coloring Book", "Remote Control Toy", "Soft Toy", "Musical Toy", "Baby Rattle", "Outdoor Ball", "Cricket Set", "Badminton Set", "Skipping Rope"] },
  { id: "books", name: "Books & Reading", subcategories: ["Children's Books", "Fiction", "Non-Fiction", "Exam Prep", "Activity Books"], products: ["Story Book", "Activity Book", "Coloring Book", "Sticker Book", "Puzzle Book", "Cookbook", "Self Help Book", "Novel", "Biography", "Exam Preparation Book", "Children's Encyclopedia"] },
  { id: "fashion", name: "Fashion & Accessories", subcategories: ["Men", "Women", "Kids", "Footwear", "Bags", "Accessories"], products: ["T-Shirt", "Shirt", "Track Pants", "Shorts", "Socks", "Innerwear", "Leggings", "Top", "Kurta", "Dupatta", "Kids T-Shirt", "Kids Shorts", "Slippers", "Flip Flops", "Sneakers", "Sandals", "Wallet", "Belt", "Cap", "Backpack", "Handbag", "Umbrella", "Sunglasses"] },
  { id: "paan", name: "Paan Corner", subcategories: ["Mouth Fresheners", "Mints", "Convenience"], products: ["Mouth Freshener", "Mint", "Gum", "Fennel", "Cardamom", "Toothpicks", "Paan Ingredients"] },
  { id: "festivals-gifting", name: "Festivals & Gifting", subcategories: ["Gifting", "Decorations", "Puja", "Festive Food", "Party Supplies"], products: ["Gift Box", "Chocolate Gift Pack", "Dry Fruit Gift Pack", "Greeting Card", "Gift Bag", "Birthday Candles", "Balloons", "Party Plates", "Party Cups", "Decorative Lights", "Diya", "Agarbatti", "Camphor", "Puja Thali", "Rakhi", "Diwali Decorations", "Holi Colors", "Christmas Decorations", "Festive Sweets"] },
  { id: "grocery-staples", name: "Grocery & Everyday Staples", subcategories: ["Packaged Food", "Canned Food", "Baking", "Condiments", "Household Consumables"], products: ["Salt", "Sugar", "Jaggery", "Vermicelli", "Papad", "Canned Beans", "Canned Corn", "Baking Soda", "Baking Powder", "Vanilla Essence", "Cocoa Powder", "Custard Powder", "Food Colour", "Corn Flour", "Bread Crumbs", "Soup", "Stock Cubes", "Instant Mix"] }
];

export const catalogProductCount = instamartCatalog.reduce((total, category) => total + category.products.length, 0);
export const catalogCategoryCount = instamartCatalog.length;

export function searchCatalog(query: string, categoryId = "all") {
  const q = query.trim().toLowerCase();
  return instamartCatalog
    .filter(category => categoryId === "all" || category.id === categoryId)
    .flatMap(category => category.products
      .filter(product => !q || product.toLowerCase().includes(q) || category.name.toLowerCase().includes(q))
      .map(product => ({ categoryId: category.id, category: category.name, product })));
}
