import { formatInr, type Product, type ProductVariant, type StoreListing, type Inventory } from "../../lib/product-catalog";
import "./catalog.css";

const categories = ["All", "Groceries", "Dairy", "Snacks", "Personal Care", "Beverages"];

const products: Array<{ product: Product; variant: ProductVariant; listing: StoreListing; inventory: Inventory; icon: string; store: string }> = [
  { product: { id: "P001", name: "Farm Fresh Milk", slug: "farm-fresh-milk", categoryId: "dairy", description: "Fresh full-cream milk.", keywords: ["milk", "dairy"], images: [], status: "ACTIVE" }, variant: { id: "V001", productId: "P001", sku: "MILK-500", name: "500 ml", attributes: { size: "500 ml" }, status: "ACTIVE" }, listing: { id: "L001", storeId: "S001", variantId: "V001", status: "ACTIVE", basePrice: { currency: "INR", minor: 3200 }, storePrice: { currency: "INR", minor: 2990 } }, inventory: { storeId: "S001", variantId: "V001", quantity: 46, reservedQuantity: 7, updatedAt: "2026-10-02T10:00:00Z" }, icon: "🥛", store: "Green Basket" },
  { product: { id: "P002", name: "Basmati Rice", slug: "basmati-rice", categoryId: "groceries", description: "Premium aged basmati rice.", keywords: ["rice", "basmati"], images: [], status: "ACTIVE" }, variant: { id: "V002", productId: "P002", sku: "RICE-5KG", name: "5 kg", attributes: { size: "5 kg" }, status: "ACTIVE" }, listing: { id: "L002", storeId: "S002", variantId: "V002", status: "ACTIVE", basePrice: { currency: "INR", minor: 68900 }, storePrice: { currency: "INR", minor: 61900 } }, inventory: { storeId: "S002", variantId: "V002", quantity: 18, reservedQuantity: 3, updatedAt: "2026-10-02T10:00:00Z" }, icon: "🍚", store: "Daily Needs" },
  { product: { id: "P003", name: "Cold Coffee", slug: "cold-coffee", categoryId: "beverages", description: "Chilled ready-to-drink coffee.", keywords: ["coffee", "drink"], images: [], status: "ACTIVE" }, variant: { id: "V003", productId: "P003", sku: "COFFEE-300", name: "300 ml", attributes: { size: "300 ml" }, status: "ACTIVE" }, listing: { id: "L003", storeId: "S003", variantId: "V003", status: "ACTIVE", basePrice: { currency: "INR", minor: 8500 }, storePrice: { currency: "INR", minor: 6990 } }, inventory: { storeId: "S003", variantId: "V003", quantity: 34, reservedQuantity: 2, updatedAt: "2026-10-02T10:00:00Z" }, icon: "☕", store: "Corner Mart" },
  { product: { id: "P004", name: "Vitamin C Face Wash", slug: "vitamin-c-face-wash", categoryId: "personal-care", description: "Daily face wash with vitamin C.", keywords: ["face wash", "vitamin c"], images: [], status: "ACTIVE" }, variant: { id: "V004", productId: "P004", sku: "FACE-100", name: "100 ml", attributes: { size: "100 ml" }, status: "ACTIVE" }, listing: { id: "L004", storeId: "S004", variantId: "V004", status: "ACTIVE", basePrice: { currency: "INR", minor: 34900 }, storePrice: { currency: "INR", minor: 28900 } }, inventory: { storeId: "S004", variantId: "V004", quantity: 22, reservedQuantity: 4, updatedAt: "2026-10-02T10:00:00Z" }, icon: "🧴", store: "WellCare" },
];

export default function CatalogPage() {
  return <main className="catalogShell">
    <header className="catalogHeader"><a href="/" className="backLink">← InstaBuy</a><span className="accountPill">Catalog</span><div className="avatar">IB</div></header>
    <section className="catalogHero"><div><p className="eyebrow">PRODUCT CATALOG</p><h1>One catalog.<br /><span>Every partner store.</span></h1><p>Canonical products stay consistent while each store controls its own price, inventory and availability.</p></div><div className="catalogStats"><div><strong>4</strong><small>Active SKUs</small></div><div><strong>4</strong><small>Partner stores</small></div><div><strong>₹1,187</strong><small>Member value</small></div></div></section>
    <section className="catalogToolbar"><div className="categoryTabs">{categories.map((category, index) => <button className={index === 0 ? "activeCat" : "cat"} key={category}>{category}</button>)}</div><div className="catalogSearch">⌕ <input placeholder="Search products, brands or SKU" /></div></section>
    <section className="catalogGrid">{products.map(({ product, variant, listing, inventory, icon, store }) => <article className="catalogCard" key={variant.sku}><div className="catalogVisual"><span>{icon}</span><label>{Math.round((1 - (listing.storePrice!.minor / listing.basePrice.minor)) * 100)}% MEMBER</label><small>{inventory.quantity - inventory.reservedQuantity} in stock</small></div><div className="catalogBody"><small className="catalogStore">{store} · {variant.name}</small><h2>{product.name}</h2><p>{product.description}</p><div className="catalogPrice"><strong>{formatInr(listing.storePrice!)}</strong><del>{formatInr(listing.basePrice)}</del></div><div className="catalogMeta"><span>SKU {variant.sku}</span><b>● Available</b></div></div></article>)}</section>
  </main>;
}
